name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    environment: development
    steps:
      - uses: actions/checkout@v4
      - run: |
          touch .env
          echo DATABASE_URL="${{ secrets.DATABASE_URL }}" >> .env
          echo API_KEY="${{ secrets.API_KEY }}" >> .env
          echo AUDIO_FILES_DIR="${{ secrets.AUDIO_FILES_DIR }}" >> .env
          echo IMAGE_FILES_DIR="${{ secrets.IMAGE_FILES_DIR }}" >> .env
          IMAGE="radio-repeater-blog:latest"
          NAME="radio-repeater-blog"

          docker stop "$NAME" || true
          docker rm --force "$NAME" || true
          docker rmi --force "$IMAGE" || true

          docker build . -t "$IMAGE" --progress=plain
          docker run --env-file .env -p 3004:3000 --name "$NAME" --restart unless-stopped -v ${{ secrets.ASSETS_FILES_DIR }}:/blog/public/assets -d "$IMAGE"
